SET ECHO ON 
DROP TABLE Person CASCADE CONSTRAINTS;
DROP TABLE Class CASCADE CONSTRAINTS;
DROP TABLE Room CASCADE CONSTRAINTS;
DROP TABLE Department CASCADE CONSTRAINTS;
DROP TABLE DepartmentLocation CASCADE CONSTRAINTS;
DROP TABLE VaccineRecord CASCADE CONSTRAINTS;
DROP TABLE VaccineTest CASCADE CONSTRAINTS;
DROP TABLE Attends CASCADE CONSTRAINTS;
DROP TABLE Residence CASCADE CONSTRAINTS;
SET ECHO OFF
select table_name from user_tables;
